# Generated by Django 2.0 on 2017-12-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='company',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='job',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
