# Generated by Django 2.0 on 2017-12-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171220_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='teamname',
            new_name='username',
        ),
    ]
