# Generated by Django 2.0 on 2017-12-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171220_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='username',
            new_name='teamname',
        ),
    ]
