# Generated by Django 2.0 on 2017-12-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171220_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='password',
        ),
    ]
