# Generated by Django 2.0 on 2017-12-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_teams_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
