# Generated by Django 2.0 on 2017-12-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_teams_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='company',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='job',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
