# Generated by Django 2.0 on 2017-12-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20171219_0453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
