# Generated by Django 2.0 on 2017-12-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('points', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('files', models.FileField(null=True, upload_to='')),
                ('flag', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=250)),
                ('solved_by', models.IntegerField(null=True)),
            ],
        ),
    ]
