# Generated by Django 2.0 on 2017-12-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_remove_challenges_solved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='files',
        ),
    ]
