# Generated by Django 2.0 on 2017-12-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_challenges_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='files',
            field=models.FileField(null=True, upload_to='uploads/<django.db.models.fields.CharField>/'),
        ),
    ]
