# Generated by Django 2.0 on 2017-12-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_auto_20171222_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='author',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='flag',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
