# Generated by Django 2.0 on 2017-12-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_auto_20171222_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/<django.db.models.fields.CharField>/'),
        ),
    ]
