# Generated by Django 2.0 on 2017-12-22 17:31

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_auto_20171222_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=challenges.models.get_upload_path),
        ),
    ]
